kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: probe
  namespace: darwin
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  rules:
  - host: poc_argo.k8s.dev.gt.intranet.pags
    http:
      paths:
      - path: /
        backend:
          serviceName: probe
          servicePort: 80
